stages:
  - pre-check
  - build


include:
  - remote: 'https://gitlab.com/sequoia-pgp/common-ci/-/raw/main/common_ci.yml'
  - component: "gitlab.com/sequoia-pgp/common-ci/rust-matrix@dvn0/add-botan3"
    inputs:
      extra_args: "-- --skip leak_tests"
