before_script:
  - if [ -d $CARGO_TARGET_DIR ]; then find $CARGO_TARGET_DIR | wc --lines; du -sh $CARGO_TARGET_DIR; fi
  - if [ -d $CARGO_HOME ]; then find $CARGO_HOME | wc --lines; du -sh $CARGO_HOME; fi
  - rustc --version
  - cargo --version
  - clang --version

after_script:
  - find $CARGO_TARGET_DIR -type f -atime +7 -delete
  - du -sh $CARGO_TARGET_DIR
  - du -sh $CARGO_HOME

buster:
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/buster:latest

  script:
    - make codespell CODESPELL_FLAGS=--summary
    - SEQUOIA_CTEST_VALGRIND=/usr/bin/valgrind make test
    - make
    - make -C tool update-usage
    - if ! git diff --quiet ; then echo "Please run 'make -C tool update-usage' and commit the result." ; false ; fi
    - make -C sqv update-usage
    - if ! git diff --quiet ; then echo "Please run 'make -C sqv update-usage' and commit the result." ; false ; fi

bullseye:
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/bullseye:latest

  script:
    - make test # XXX: We cannot currently use valgrind, https://github.com/rust-lang/rust/issues/68979
    - make
    - make -C tool update-usage
    - if ! git diff --quiet ; then echo "Please run 'make -C tool update-usage' and commit the result." ; false ; fi
    - make -C sqv update-usage
    - if ! git diff --quiet ; then echo "Please run 'make -C sqv update-usage' and commit the result." ; false ; fi

  variables:
    CARGO_TARGET_DIR: $CI_PROJECT_DIR/../target-bullseye
    RUSTFLAGS: -D warnings -A unused-parens

rust-stable:
  stage: build
  image: rust:1-slim-buster

  before_script:
    - apt update -y -qq
    - apt install --no-install-recommends -y -qq -o=Dpkg::Use-Pty=0 clang libclang-dev llvm pkg-config nettle-dev
    - if [ -d $CARGO_TARGET_DIR ]; then find $CARGO_TARGET_DIR | wc --lines; du -sh $CARGO_TARGET_DIR; fi
    - if [ -d $CARGO_HOME ]; then find $CARGO_HOME | wc --lines; du -sh $CARGO_HOME; fi
    - rustc --version
    - cargo --version
    - clang --version

  script:
    - cargo test -p buffered-reader -p sequoia-openpgp -p sequoia-sqv

  variables:
    CARGO_TARGET_DIR: $CI_PROJECT_DIR/../target-rust-stable
    RUSTFLAGS: -D warnings -A unused-parens

variables:
  DEBIAN_FRONTEND: noninteractive
  CARGO_HOME: $CI_PROJECT_DIR/../cargo
  CARGO_TARGET_DIR: $CI_PROJECT_DIR/../target
  CARGO_FLAGS: --color always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  CFLAGS: -Werror
