[workspace]
resolver = "2"
members = [
    "autocrypt",
    "buffered-reader",
    "guide",
    "ipc",
    "net",
    "openpgp",
]

[profile.release]
debug = true

[patch.crates-io]
anyhow = { git = 'https://github.com/dtolnay/anyhow.git', rev = 'd6acd22200de94b65804e08ca41a4bdff3404512' }
