[target.'cfg(all())']
# Note: if the RUSTFLAGS environment variable is set, this will be
# ignored.
rustflags = [
          "-Dwarnings",
          "-Aunused-parens",
          "-Aclippy::collapsible-else-if",
          "-Aclippy::needless-question-mark",
          "-Aclippy::redundant-clone",
          "-Aclippy::try-err",
          "-Aclippy::unnecessary-lazy-evaluations",
          "-Aclippy::manual-map",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
