[package]
name = "sequoia-net"
description = "Network services for OpenPGP"
version = "0.6.0"
authors = [
    "Justus Winter <justus@sequoia-pgp.org>",
    "Kai Michaelis <kai@sequoia-pgp.org>",
    "Neal H. Walfield <neal@sequoia-pgp.org>",
]
documentation = "https://docs.sequoia-pgp.org/0.6.0/sequoia_net"
homepage = "https://sequoia-pgp.org/"
repository = "https://gitlab.com/sequoia-pgp/sequoia"
readme = "../README.md"
keywords = ["cryptography", "openpgp", "pgp", "hkp", "keyserver"]
categories = ["cryptography", "authentication", "email"]
license = "GPL-3.0"

[badges]
gitlab = { repository = "sequoia-pgp/sequoia" }
maintenance = { status = "actively-developed" }

[dependencies]
sequoia-openpgp = { path = "../openpgp", version = "0.6" }
sequoia-core = { path = "../core", version = "0.6" }

capnp-rpc = "0.9"
failure = "0.1.2"
fs2 = "0.4.2"
futures = "0.1"
http = "0.1.5"
hyper = "0.12"
hyper-tls = "0.3"
libc = "0.2.33"
memsec = "0.5.4"
native-tls = "0.2.0"
nettle = "5.0"
percent-encoding = "1.0.1"
rand = "0.6"
tokio-core = "0.1"
tokio-io = "0.1.4"
url = "1.6.0"
zbase32 = "0.1.2"